apiVersion: v1
kind: Service
metadata:
  name: traffic-gateway-service
spec:
  type: NodePort
  selector:
    app: standard-workstation 
  ports:
    - port: 80 # The port exposed by the Service inside the cluster.
      targetPort: 5000 #port flask is listening on inside the pod
      nodePort: 30008 # The port exposed on the Kubernetes node.


