apiVersion: v1
kind: Pod
metadata:
  name: standard-workstation
  labels:
    app: standard-workstation 
spec:
  containers:
    - name: standard-worker
      image: localhost:5000/standard_worker:latest
      ports:
        - containerPort: 5000